config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'

  authenticated :user, ->(user) { user.has_role? :admin }  do
    mount Sidekiq::Web => '/sidekiq'
  end

  authenticated :user do
    root to: 'users/images#show'
  end

  devise_for :users, controllers: {
    omniauth_callbacks: 'omniauth_callbacks',
    masquerades: 'admin/masquerades'
  }

  get 'become_partner' => 'partner#index', as: :become_partner
  root 'landing_page#index'

  resources :taddar_mentions, only: %i(create index)

  namespace :pages do
    resources :contact_us, only: %i(create index)
    resources :demo, only: %i(index)
  end

  namespace :users do
    resources :products, only: %i(show)
  end

  delete 'logout' => 'sessions#destroy'
  get 'instagram_authenticate' => 'instagram#authenticate'
  get '/auth/instagram/callback' => 'instagram#call_back'
  get '/privacy_policy' => 'policies#privacy_policy'
  get '/terms_and_conditions' => 'policies#terms_and_conditions'

  resources :users, only: %i(update destroy)
  resources :cropped_images, only: %i(create update)
  resources :similar_products, only: [:index]

  get 'landing_page' => 'landing_page#index'
  get 'influencer' => 'landing_page#influencer'

  namespace :admin do
    namespace :crawling do
      post 'taddar_vision_export' => 'taddar_vision_export#create', as: :taddar_vision_export
      resources :product_crawlers, except: [:show] do
        member do
          post :execute
        end
        resources :crawl_categories, only: %i(create update destroy)
        resources :root_categories, only: :show
      end
    end

    namespace :commission_factory do
      resources :importers, except: [:show] do
        member do
          post :execute
        end
        resources :categories, only: %i(create update destroy) do
          member do
            post :execute
          end
        end
        resources :root_categories, only: :show
        resources :products_destroyer, only: :create
      end
    end

    resources :users, except: [:show]
    resources :proxies, except: [:show]
  end

  resources :search, only: [:index] do
    collection do
      get :products
      get :users
    end
  end

  namespace :api do
    namespace :v1 do
      resources :similar_products, only: %i(create)
      resources :products, only: %i(index show), param: :uuid
      resources :instagram_authentication, only: [:index]
      resources :users, only: %i(show update), param: :uuid
      resources :instagram_posts, only: %i(index)
      resources :image_of_interests, only: %i(index create destroy show), param: :uuid
      resources :cropped_products, only: %i(create), param: :uuid
      get '/token' => 'instagram_authentication#token'
      resources :search, only: [:index] do
        collection do
          get :products
          get :users
        end
      end
    end
  end

  get ':id' => 'users/outfits#show', as: :user_outfits
  get ':id/images' => 'users/images#show', as: :user_images

  resources :users, only: [], path: ':username' do
    collection do
      resources :categories, only: [:index] do
        member do
          get :products
        end

        collection do
          get :hierachy
        end
      end

      get 'setup' => 'setup#edit'
      get 'complete' => 'setup#complete'
      patch 'update_profile' => 'setup#update_profile'
      get 'my_account' => 'users#my_account'
      get 'instagram_images' => 'instagram#instagram_images'
    end
  end
end

app/models/proxy.rb
class Proxy < ApplicationRecord
  validates :ip, presence: true

  def to_phantomjs_options
    result = []
    return result if ip.blank?
    result << "--proxy=#{[ip, port].select(&:present?).join(':')}"
    return result if user.blank? || password.blank?
    result + ["--proxy-auth=#{user}:#{password}"]
  end

  def to_nokogiri_options
    options =
      if user.present? && password.present?
        {
          proxy_http_basic_authentication: [full_http_address, user, password]
        }
      else
        { proxy: full_http_address }
      end
    options['User-Agent'] = user_agent if user_agent.present?
    options
  end

  def full_address
    [ip, port].select(&:present?).join(':')
  end

  def full_http_address
    "http://#{full_address}"
  end

  def self.sample
    (all.to_a + [nil]).sample
  end

  def self.sample_nokogiri_options
    sample&.to_nokogiri_options || {}
  end
end

app/controllers/admin/proxies_controller.rb
class Admin::ProxiesController < Admin::BaseController
  before_action :set_proxy, only: %i(edit update destroy)

  def index
    @proxies = Proxy.all
  end

  def new
    @proxy = Proxy.new
  end

  def create
    @proxy = Proxy.new(proxy_params)

    if @proxy.save
      flash[:success] = 'Created'
      redirect_to admin_proxies_path
    else
      flash[:danger] = "Errors: #{@proxy.errors.full_messages.to_sentence}"
      render :new
    end
  end

  def edit
  end

  def update
    if @proxy.update(proxy_params)
      flash[:success] = 'Updated'
      redirect_to admin_proxies_path
    else
      flash[:danger] = "Errors: #{@proxy.errors.full_messages.to_sentence}"
      render :edit
    end
  end

  def destroy
    @proxy.destroy
    flash[:success] = 'Deleted'
    redirect_to admin_proxies_path
  end

  private

  def set_proxy
    @proxy = Proxy.find(params[:id])
  end

  def proxy_params
    params.require(:proxy).permit(:ip, :port, :user, :password, :user_agent)
  end
end

app/views/admin/proxies/_form.html.haml
= simple_form_for [:admin, @proxy] do |f|
  .form-section
    = f.input :ip
    = f.input :port
    = f.input :user
    = f.input :password
    = f.input :user_agent
  .form-submit
    = f.button :submit, class: 'button button-red'

app/views/admin/proxies/edit.html.haml
.flex-auto.bg-grey-xxlight
  .container.py10
    .flex.justify-center
      .form-half
        .mb10
          .mb6.flex.justify-between.items-center
            %h2.mb0 Edit Proxy

          .bg-white.p6.rounded
            .flex.flex-column
              = render 'form'

app/views/admin/proxies/index.html.haml
.flex-auto
  .container.py10
    .flex.justify-between.mb4
      %h2.mb0 Proxies
      %p
        = link_to 'New Proxy', new_admin_proxy_path, class: 'button button-red'

    %table#example
      %thead
        %tr
          %th.left-align Ip address
          %th.left-align User Agent
          %th.right-align.no-sort Actions
      %tbody
        - @proxies.each do |proxy|
          %tr
            %td.left-align= proxy.full_address
            %td.left-align= proxy.user_agent
            %td.right-align
              = link_to edit_admin_proxy_path(proxy), title: 'Edit' do
                %i.fa.fa-pencil
              = link_to admin_proxy_path(proxy), method: :delete, data: { confirm: 'Are you sure?' }, title: 'Delete' do
                %i.fa.fa-trash

app/views/admin/proxies/new.html.haml
.flex-auto.bg-grey-xxlight
  .container.py10
    .flex.justify-center
      .form-half
        .mb10
          .mb6.flex.justify-between.items-center
            %h2.mb0 Create Proxy

          .bg-white.p6.rounded
            .flex.flex-column
              = render 'form'