config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'

  authenticated :user, ->(user) { user.has_role? :admin }  do
    mount Sidekiq::Web => '/sidekiq'
  end

  authenticated :user do
    root to: 'users/images#show'
  end

  devise_for :users, controllers: {
    omniauth_callbacks: 'omniauth_callbacks',
    masquerades: 'admin/masquerades'
  }

  get 'become_partner' => 'partner#index', as: :become_partner
  root 'landing_page#index'

  resources :taddar_mentions, only: %i(create index)

  namespace :pages do
    resources :contact_us, only: %i(create index)
    resources :demo, only: %i(index)
  end

  namespace :users do
    resources :products, only: %i(show)
  end

  delete 'logout' => 'sessions#destroy'
  get 'instagram_authenticate' => 'instagram#authenticate'
  get '/auth/instagram/callback' => 'instagram#call_back'
  get '/privacy_policy' => 'policies#privacy_policy'
  get '/terms_and_conditions' => 'policies#terms_and_conditions'

  resources :users, only: %i(update destroy)
  resources :cropped_images, only: %i(create update)
  resources :similar_products, only: [:index]

  get 'landing_page' => 'landing_page#index'
  get 'influencer' => 'landing_page#influencer'

  namespace :admin do
    namespace :crawling do
      post 'taddar_vision_export' => 'taddar_vision_export#create', as: :taddar_vision_export
      resources :product_crawlers, except: [:show] do
        member do
          post :execute
        end
        resources :crawl_categories, only: %i(create update destroy)
        resources :root_categories, only: :show
      end
    end

    namespace :commission_factory do
      resources :importers, except: [:show] do
        member do
          post :execute
        end
        resources :categories, only: %i(create update destroy) do
          member do
            post :execute
          end
        end
        resources :root_categories, only: :show
        resources :products_destroyer, only: :create
      end
    end

    resources :users, except: [:show]
    resources :proxies, except: [:show]
  end

  resources :search, only: [:index] do
    collection do
      get :products
      get :users
    end
  end

  namespace :api do
    namespace :v1 do
      resources :similar_products, only: %i(create)
      resources :products, only: %i(index show), param: :uuid
      resources :instagram_authentication, only: [:index]
      resources :users, only: %i(show update), param: :uuid
      resources :instagram_posts, only: %i(index)
      resources :image_of_interests, only: %i(index create destroy show), param: :uuid
      resources :cropped_products, only: %i(create), param: :uuid
      get '/token' => 'instagram_authentication#token'
      resources :search, only: [:index] do
        collection do
          get :products
          get :users
        end
      end
    end
  end

  get ':id' => 'users/outfits#show', as: :user_outfits
  get ':id/images' => 'users/images#show', as: :user_images

  resources :users, only: [], path: ':username' do
    collection do
      resources :categories, only: [:index] do
        member do
          get :products
        end

        collection do
          get :hierachy
        end
      end

      get 'setup' => 'setup#edit'
      get 'complete' => 'setup#complete'
      patch 'update_profile' => 'setup#update_profile'
      get 'my_account' => 'users#my_account'
      get 'instagram_images' => 'instagram#instagram_images'
    end
  end
end

app/controllers/admin/commission_factory/categories_controller.rb
class Admin::CommissionFactory::CategoriesController < ApplicationController
  before_action :set_crawler

  def create
    result = crawl_category_params[:category_ids].map do |category_id|
      crawl_category = @commission_factory_importer.commission_factory_categories.build(
        query: commission_factory_category_params[:query],
        category_id: category_id
      )
      crawl_category.save
    end

    if result.include?(false)
      flash[:error] = 'Cannot add categories to crawler'
    else
      flash[:success] = 'Categories added to crawler'
    end

    redirect_back(fallback_location: [:edit, :admin, :crawling, @commission_factory_importer])
  end

  def destroy
    destroyer = ::CommissionFactory::DestroyCategoryService.new(commission_factory_category).tap(&:call)
    if destroyer.errors.none?
      flash[:success] = 'Category removed from crawler'
    else
      flash[:error] = destroyer.errors.first
    end
    redirect_back(fallback_location: [:edit, :admin, :crawling, @commission_factory_importer])
  end

  def execute
    ::CommissionFactory::ImportProductsService.new(CommissionFactoryCategory.find(params[:id])).call
    flash[:success] = 'Crawling started'
    redirect_back(fallback_location: [:edit, :admin, :crawling, @commission_factory_importer])
  end

  private

  def set_crawler
    @commission_factory_importer = CommissionFactoryImporter.find(params[:importer_id])
  end

  def crawl_category_params
    params.require(:crawl_category).permit(category_ids: [])
  end

  def commission_factory_category_params
    params.require(:commission_factory_category).permit(:query)
  end

  def commission_factory_category
    @commission_factory_importer.commission_factory_categories.find(params[:id])
  end
end

app/controllers/admin/commission_factory/importers_controller.rb
class Admin::CommissionFactory::ImportersController < Admin::BaseController
  before_action :set_crawler, only: %i(edit update destroy execute)

  def index
    @crawlers = CommissionFactoryImporter.all
  end

  def new
    @crawler = CommissionFactoryImporter.new
  end

  def create
    @crawler = CommissionFactoryImporter.new(crawler_params)

    if @crawler.save
      flash[:success] = 'Created'
      redirect_to admin_commission_factory_importers_path
    else
      flash[:danger] = "Errors: #{@crawler.errors.full_messages.to_sentence}"
      render :new
    end
  end

  def edit
  end

  def update
    if @crawler.update(crawler_params)
      flash[:success] = 'Updated'
      redirect_to admin_commission_factory_importers_path
    else
      flash[:danger] = "Errors: #{@crawler.errors.full_messages.to_sentence}"
      render :edit
    end
  end

  def destroy
    @crawler.destroy
    flash[:success] = 'Deleted'
    redirect_to admin_commission_factory_importers_path
  end

  def execute
    @crawler.commission_factory_categories.each do |commission_factory_category|
      ::CommissionFactory::ImportProductsService.new(commission_factory_category).call
    end

    flash[:success] = 'The process has been started in background. Please come back later.'
    redirect_to admin_commission_factory_importers_path
  end

  private

  def set_crawler
    @crawler = CommissionFactoryImporter.find(params[:id])
  end

  def crawler_params
    params.require(:commission_factory_importer).permit(:user_id, :csv)
  end
end

app/controllers/admin/commission_factory/products_destroyer_controller.rb
class Admin::CommissionFactory::ProductsDestroyerController < Admin::BaseController
  before_action :set_products

  def create
    if @products.any?
      flash[:notice] = 'Products are being destroyed'
      @products.each do |product|
        Products::DestroyerWorker.perform_async(product.id)
      end
    else
      flash[:error] = 'Error destroying products'
    end

    redirect_to(:back, fallback: root_path)
  end

  private

  def set_products
    if params[:commission_factory_category_id].present?
      user_category_products
    else
      @products = CommissionFactoryImporter.find(params[:importer_id]).user.products if params[:importer_id]
      @products = @products.where(crawled: false) if params[:crawled] == 'false'
    end
  end

  def user_category_products
    user_category = UserCategory.find_by(
      category: CommissionFactoryCategory.find(params[:commission_factory_category_id]).category,
      user:  CommissionFactoryImporter.find(params[:crawler_id]).user
    )

    @products = UserCategoryProduct.where(user_category: user_category).map(&:product)
  end
end

app/controllers/admin/commission_factory/root_categories_controller.rb
class Admin::CommissionFactory::RootCategoriesController < ApplicationController
  def show
    @importer = CommissionFactoryImporter.find(params[:importer_id])
    @category = Category.find(params[:id])
    @root_category = @importer.commission_factory_categories.find_or_create_by(category: @category)
    @commission_factory_category = @importer.commission_factory_categories.new
  end
end

app/views/admin/commission_factory/importers/edit.haml
.flex-auto.bg-grey-xxlight.min-h100vh
  .container.py5
    .flex
      .font-large.pr2
        Webhose Crawler / #{@crawler.user.username}
      = link_to 'Crawl', execute_admin_commission_factory_importer_path(@crawler, modify: true), method: :post, data: { confirm: 'Are you sure you want to crawl commission factory?' }, class: 'button button-blue mr2'
      = link_to 'Delete Uncrawled Products', admin_commission_factory_importer_products_destroyer_index_path(@crawler, crawled: false), method: :post, data: { confirm: "Are you sure you want to delete all products that haven't been crawled?" }, class: 'button button-red mr2'
      = link_to 'Delete All Products', admin_commission_factory_importer_products_destroyer_index_path(@crawler), method: :post, data: { confirm: 'Are you sure you want to delete all products?' }, class: 'button button-red'
    .my5.bg-white.p6
      .flex.items-center.crawler-menu
        = link_to 'Settings', edit_admin_commission_factory_importer_path(@crawler), class: 'active'
        - Category.roots.each do |category|
          = link_to "#{category.name.capitalize} Categories", admin_commission_factory_importer_root_category_path(@crawler, category)
      = simple_form_for @crawler, url: admin_commission_factory_importer_path, method: :patch do |f|
        .form-section
          = f.input :user_id, label: 'User', collection: User.all, value_method: :id, label_method: :username, selected: @crawler.user_id
          - if f.object.csv.present?
            %p.bold Current CSV
            = link_to f.object.csv.original_filename, f.object.csv.url
          = f.input :csv, as: :file
          .right-align.mt2
            = f.submit 'Save', class: 'button button-wide button-blue'

app/views/admin/commission_factory/importers/index.haml
.flex-auto.bg-grey-xxlight.min-h100vh
  .container.py5
    .flex.justify-between
      .font-large Commission Factory Importer
      = link_to 'Create', new_admin_commission_factory_importer_path, class: 'button button-wide button-blue'
    .my5.bg-white.p6
      %table#example
        %thead
          %tr
            %th.left-align User
            %th.right-align.no-sort Actions
        %tbody
          - @crawlers.each do |crawler|
            %tr
              %td.left-align= link_to crawler.user.username, user_outfits_path(crawler.user)
              %td.right-align
                = link_to 'Crawl', execute_admin_commission_factory_importer_path(crawler, modify: true), method: :post, data: { confirm: 'Are you sure you want to import commission factory?' }, class: 'text-green'
                = link_to 'Edit', edit_admin_commission_factory_importer_path(crawler), class: 'text-blue'
                = link_to 'Delete', admin_commission_factory_importer_path(crawler), method: :delete, data: { confirm: 'Are you sure?' }, class: 'text-red'

app/views/admin/commission_factory/importers/new.haml
.flex-auto.bg-grey-xxlight.min-h100vh
  .container.py5
    .font-large New Commission Factory Importer
    .my5.bg-white.p6
      = simple_form_for @crawler, url: admin_commission_factory_importers_path, method: :post do |f|
        .form-section
          = f.input :user_id, label: 'User', collection: User.all, value_method: :id, label_method: :username, selected: @crawler.user_id
        .right-align.mt2
          = f.submit 'Save', class: 'button button-wide button-blue'