config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'

  authenticated :user, ->(user) { user.has_role? :admin }  do
    mount Sidekiq::Web => '/sidekiq'
  end

  authenticated :user do
    root to: 'users/images#show'
  end

  devise_for :users, controllers: {
    omniauth_callbacks: 'omniauth_callbacks',
    masquerades: 'admin/masquerades'
  }

  get 'become_partner' => 'partner#index', as: :become_partner
  root 'landing_page#index'

  resources :taddar_mentions, only: %i(create index)

  namespace :pages do
    resources :contact_us, only: %i(create index)
    resources :demo, only: %i(index)
  end

  namespace :users do
    resources :products, only: %i(show)
  end

  delete 'logout' => 'sessions#destroy'
  get 'instagram_authenticate' => 'instagram#authenticate'
  get '/auth/instagram/callback' => 'instagram#call_back'
  get '/privacy_policy' => 'policies#privacy_policy'
  get '/terms_and_conditions' => 'policies#terms_and_conditions'

  resources :users, only: %i(update destroy)
  resources :cropped_images, only: %i(create update)
  resources :similar_products, only: [:index]

  get 'landing_page' => 'landing_page#index'
  get 'influencer' => 'landing_page#influencer'

  namespace :admin do
    namespace :crawling do
      post 'taddar_vision_export' => 'taddar_vision_export#create', as: :taddar_vision_export
      resources :product_crawlers, except: [:show] do
        member do
          post :execute
        end
        resources :crawl_categories, only: %i(create update destroy)
        resources :root_categories, only: :show
      end
    end

    namespace :commission_factory do
      resources :importers, except: [:show] do
        member do
          post :execute
        end
        resources :categories, only: %i(create update destroy) do
          member do
            post :execute
          end
        end
        resources :root_categories, only: :show
        resources :products_destroyer, only: :create
      end
    end

    resources :users, except: [:show]
    resources :proxies, except: [:show]
  end

  resources :search, only: [:index] do
    collection do
      get :products
      get :users
    end
  end

  namespace :api do
    namespace :v1 do
      resources :similar_products, only: %i(create)
      resources :products, only: %i(index show), param: :uuid
      resources :instagram_authentication, only: [:index]
      resources :users, only: %i(show update), param: :uuid
      resources :instagram_posts, only: %i(index)
      resources :image_of_interests, only: %i(index create destroy show), param: :uuid
      resources :cropped_products, only: %i(create), param: :uuid
      get '/token' => 'instagram_authentication#token'
      resources :search, only: [:index] do
        collection do
          get :products
          get :users
        end
      end
    end
  end

  get ':id' => 'users/outfits#show', as: :user_outfits
  get ':id/images' => 'users/images#show', as: :user_images

  resources :users, only: [], path: ':username' do
    collection do
      resources :categories, only: [:index] do
        member do
          get :products
        end

        collection do
          get :hierachy
        end
      end

      get 'setup' => 'setup#edit'
      get 'complete' => 'setup#complete'
      patch 'update_profile' => 'setup#update_profile'
      get 'my_account' => 'users#my_account'
      get 'instagram_images' => 'instagram#instagram_images'
    end
  end
end

app/models/product_crawler.rb
class ProductCrawler < ApplicationRecord
  belongs_to :user

  has_many :products, dependent: :destroy
  has_many :crawl_categories, dependent: :destroy
  has_many :categories, through: :crawl_categories

  alias_attribute :merchant, :base_url
end

app/controllers/admin/crawling/crawl_categories_controller.rb
class Admin::Crawling::CrawlCategoriesController < ApplicationController
  before_action :set_crawler

  def create
    result = crawl_category_params[:category_ids].map do |category_id|
      crawl_category = @product_crawler.crawl_categories.build(
        url: crawl_category_params[:url],
        category_id: category_id
      )
      crawl_category.save
    end

    if result.include?(false)
      flash[:error] = 'Cannot add categories to crawler'
    else
      flash[:success] = 'Categories added to crawler'
    end

    redirect_back(fallback_location: [:edit, :admin, :crawling, @product_crawler])
  end

  def update
    crawl_category = @product_crawler.crawl_categories.find(params[:id])

    if crawl_category.update(update_params)
      flash[:success] = 'Settings updated'
    else
      flash[:error] = 'Cannot update the settings'
    end

    redirect_back(fallback_location: [:edit, :admin, :crawling, @product_crawler])
  end

  def destroy
    crawl_category = @product_crawler.crawl_categories.find(params[:id])
    crawl_category.destroy

    flash[:success] = 'Category removed from crawler'

    redirect_back(fallback_location: [:edit, :admin, :crawling, @product_crawler])
  end

  private

  def set_crawler
    @product_crawler = ProductCrawler.find(params[:product_crawler_id])
  end

  def crawl_category_params
    params.require(:crawl_category).permit(:url, category_ids: [])
  end

  def update_params
    params.require(:crawl_category).permit(:viglink_category)
  end
end

app/controllers/admin/crawling/product_crawlers_controller.rb
class Admin::Crawling::ProductCrawlersController < Admin::BaseController
  before_action :set_crawler, only: %i(edit update destroy execute)
  before_action :set_viglink, only: %i(index new)

  def index
    @product_crawlers = ProductCrawler.where(viglink: @viglink)
  end

  def new
    @product_crawler = ProductCrawler.new(viglink: @viglink)
  end

  def create
    @product_crawler = ProductCrawler.new(product_crawler_params)

    if @product_crawler.save
      flash[:success] = 'Created'
      redirect_to admin_crawling_product_crawlers_path(viglink: @product_crawler.viglink)
    else
      flash[:danger] = "Errors: #{@product_crawler.errors.full_messages.to_sentence}"
      render :new
    end
  end

  def edit
  end

  def update
    if @product_crawler.update(product_crawler_params)
      flash[:success] = 'Updated'
      redirect_to admin_crawling_product_crawlers_path(viglink: @product_crawler.viglink)
    else
      flash[:danger] = "Errors: #{@product_crawler.errors.full_messages.to_sentence}"
      render :edit
    end
  end

  def destroy
    @product_crawler.destroy
    flash[:success] = 'Deleted'
    redirect_to admin_crawling_product_crawlers_path(viglink: @product_crawler.viglink)
  end

  def execute
    CrawlJob.perform_later(@product_crawler.id, params[:modify])
    flash[:success] = 'The process has been started in background. Please come back later.'
    redirect_to admin_crawling_product_crawlers_path(viglink: @product_crawler.viglink)
  end

  private

  def set_crawler
    @product_crawler = ProductCrawler.find(params[:id])
  end

  def set_viglink
    @viglink = params[:viglink].present? && params[:viglink] == 'true'
  end

  def product_crawler_params
    params.require(:product_crawler).permit(
      :location, :product_link_css, :load_more_css, :paginated,
      :title_css, :price_css, :description_css, :strip_css, :viglink,
      :user_id, :image_css, :image_attribute, :image_regex, :base_url, :js
    )
  end
end

app/controllers/admin/crawling/root_categories_controller.rb
class Admin::Crawling::RootCategoriesController < ApplicationController
  def show
    @product_crawler = ProductCrawler.find(params[:product_crawler_id])
    @category = Category.find(params[:id])
    @root_crawl_category =
      @product_crawler.crawl_categories.find_or_create_by(category: @category)
    @crawl_category = @product_crawler.crawl_categories.new
  end
end

app/controllers/admin/crawling/taddar_vision_export_controller.rb
class Admin::Crawling::TaddarVisionExportController < Admin::BaseController
  def create
    @products = ProductCrawler.find(params[:id]).products
    @products.each do |product|
      TaddarVisionJob.perform_later(product) if product.images.any?
    end
  end
end

app/views/admin/crawling/product_crawlers/edit.html.haml
.flex-auto.bg-grey-xxlight.min-h100vh
  .container.py5
    .font-large #{@product_crawler.user.username} / #{@product_crawler.base_url.gsub(/.*?:\/\//, '')}
    .my5.bg-white.p6
      .flex.items-center.crawler-menu
        = link_to 'Settings', '#', class: 'active'
        - Category.roots.each do |category|
          = link_to "#{category.name.capitalize} Categories", admin_crawling_product_crawler_root_category_path(@product_crawler, category)
      = simple_form_for [:admin, :crawling, @product_crawler] do |f|
        .form-section
          = f.input :user_id, label: 'User', collection: User.all, value_method: :id, label_method: :username, selected: @product_crawler.user_id
          = f.input :base_url, label: @product_crawler.viglink ? 'Merchant' : 'Brands base url'
          = f.label :location
          = f.country_select :location, ['Australia', 'United States', 'United Kingdom'], required: true
          = f.input :product_link_css
          = f.input :title_css
          = f.input :price_css
          = f.input :description_css
          = f.input :image_css
          = f.input :image_attribute
          = f.input :image_regex
          = f.input :load_more_css
          = f.input :js, label: 'Crawl by javascript?'
          = f.input :paginated, label: 'Crawl page-by-page?'
          .right-align.mt2
            = f.submit 'Save', class: 'button button-wide button-blue'

app/views/admin/crawling/product_crawlers/index.html.haml
.flex-auto.bg-grey-xxlight.min-h100vh
  .container.py5
    .flex.justify-between
      .font-large #{'Viglink' if @viglink} Website Crawlers
      = link_to 'Create', new_admin_crawling_product_crawler_path(viglink: @viglink), class: 'button button-wide button-blue'
    .my5.bg-white.p6
      %table#example
        %thead
          %tr
            %th.left-align User
            %th.left-align= @viglink ? 'Merchant' : 'Base URL'
            %th.right-align.no-sort Actions
        %tbody
          - @product_crawlers.each do |product_crawler|
            %tr
              %td.left-align= link_to product_crawler.user.username, user_outfits_path(product_crawler.user)
              %td.left-align= product_crawler.base_url
              %td.right-align
                = link_to edit_admin_crawling_product_crawler_path(product_crawler), title: 'Edit' do
                  %i.fa.fa-pencil
                = link_to admin_crawling_taddar_vision_export_path(id: product_crawler.id), title: 'Export to taddar vision', method: :post do
                  %i.fa.fa-upload
                = link_to execute_admin_crawling_product_crawler_path(product_crawler, modify: true), title: 'Crawl and modify existing (Slow)', method: :post do
                  %i.fa.fa-arrow-circle-down
                = link_to execute_admin_crawling_product_crawler_path(product_crawler), title: 'Crawl and ignore existing (Quick)', method: :post do
                  %i.fa.fa-arrow-down
                = link_to admin_crawling_product_crawler_path(product_crawler), method: :delete, data: { confirm: 'Are you sure?' }, title: 'Delete' do
                  %i.fa.fa-trash

app/views/admin/crawling/product_crawlers/new.html.haml
.flex-auto.bg-grey-xxlight.min-h100vh
  .container.py5
    .font-large New Crawler
    .my5.bg-white.p6
      = simple_form_for [:admin, :crawling, @product_crawler] do |f|
        .form-section
          = f.input :user_id, label: 'User', collection: User.all, value_method: :id, label_method: :username, selected: @product_crawler.user_id
          = f.input :base_url, label: @product_crawler.viglink ? 'Merchant' : 'Brands base url'
          - if @product_crawler.viglink
            = f.input :viglink, label: 'Viglink crawler?'
        .right-align.mt2
          = f.submit 'Save', class: 'button button-wide button-blue'